5 add main page
Dergacz/pokemon pull request #6
Opened 2022-12-09 15:36 UTC by Dergacz

2022-12-12 19:43 UTC, melonholy requested changes

2022-12-12 19:43 UTC, melonholy commented on .eslintrc.yml
> +  - 'import'
new line

2022-12-12 19:43 UTC, melonholy commented on app.tsx
> +        <MainPage/>
did you applied prettier seems like you have 4 spaces on tab instead of 2?

2022-12-12 19:43 UTC, melonholy commented on src/components/MainPage.tsx
> +import { FC } from 'react';
Don't duplicate react import

2022-12-12 19:43 UTC, melonholy commented on src/components/MainPage.tsx
> +                pokemons && pokemons.results.map(pokemon => (
it's better to use pokemons?.results.map instead of check

2022-12-12 19:43 UTC, melonholy commented on src/components/MainPage.tsx
> +        <div>
Maybe you should move it in separate component like PokemonsList

2022-12-12 19:43 UTC, melonholy commented on src/components/Pokemon.tsx
> +};
new line

2022-12-12 19:43 UTC, melonholy commented on src/models/models.ts
> +}
new line

2022-12-12 19:43 UTC, melonholy commented on src/models/models.ts
> +
i think it's better to have file named [ComponentFolderName].types.ts in component folder
and lets make folder structure for components smth like this
![image](https://user-images.githubusercontent.com/36301981/207138589-915bb327-6952-4d1e-b085-7d2319b34083.png)

2022-12-12 19:43 UTC, melonholy commented on src/services/PokemonServiceApi.ts
> +});
new line

2022-12-16 12:01 UTC, Dergacz commented on src/components/MainPage.tsx
> +                pokemons && pokemons.results.map(pokemon => (
the request takes time to pass, so the pokemons will be undefined for a while

2022-12-19 11:23 UTC, melonholy commented on src/components/MainPage.tsx
> +                pokemons && pokemons.results.map(pokemon => (
yes, but optional chaining will prevent further operations

2022-12-21 14:48 UTC, merged