7 add paggination
Dergacz/pokemon pull request #9
Opened 2023-01-11 15:31 UTC by Dergacz

2023-01-24 14:00 UTC, melonholy requested changes

2023-01-24 14:00 UTC, melonholy commented on src/reducers/pokemonSlice.ts
> +      state.pokemonsArray.sort((a, b) => (a.id > b.id ? 1 : -1));
i would recommend you to create another array, sort it and then assign it to your `pokemonsArray `. In your case it will possibly cause the unexpected mutations

2023-01-24 14:00 UTC, melonholy commented on src/scenes/MainPage/MainPage.tsx
> +  }, [pokemons, pokemons && pokemons.next]);
Can you pls explain what is this for?

2023-01-24 14:00 UTC, melonholy commented on src/scenes/MainPage/MainPage.tsx
> +  const count = pokemons && pokemons.count;
you can use `pokemons?.count` instead of `pokemons && pokemons.count;`

2023-01-24 14:00 UTC, melonholy commented on src/scenes/Pokemon/Pokemon.tsx
> +  const pokemon = pokemonsArray.find((p) => p.name === title);
Since it search function let's wrap it in memo

2023-01-24 14:00 UTC, melonholy commented on src/scenes/Pokemon/Pokemon.tsx
> +  const [{ color }] = pokemonTypes.filter(
Can we make it more readable?)))
we can discuss it if you have strong opinion on it

2023-01-24 14:00 UTC, melonholy commented on src/scenes/PokemonCard/PokemonCard.tsx
> +  const [{ color }] = pokemonTypes.filter(
i saw this before, so let's move it to separate utility function

2023-01-24 14:00 UTC, melonholy commented on src/scenes/PokemonList/PokemonList.tsx
> +      <Grid.Container gap={2} style={{ justifyContent: 'space-between' }}>
why do we pass `justifyContent ` in style tag?

2023-01-24 14:00 UTC, melonholy commented on src/scenes/PokemonList/PokemonList.tsx
> +              <Grid xs={4} key={pokemon.id} style={{ flexBasis: '0' }}>
see comment above

2023-01-24 14:00 UTC, melonholy commented on src/utils/pokemonTypes.ts
> +export const pokemonTypes = [
i don't think we need it you can only describe name values and type the color as a string

2023-01-24 14:02 UTC, melonholy reviewed
<img width="747" alt="image" src="https://user-images.githubusercontent.com/36301981/214314470-624d132f-8db1-4027-b723-097af093f544.png">

Lets make header and pagination fixed and place the content between them

2023-01-24 14:03 UTC, melonholy reviewed
<img width="285" alt="image" src="https://user-images.githubusercontent.com/36301981/214314918-6d5fd998-0132-49d1-a37a-30bd07ef32bd.png">

Why you named it like this?)

2023-01-25 13:11 UTC, Dergacz commented on src/scenes/PokemonList/PokemonList.tsx
> +      <Grid.Container gap={2} style={{ justifyContent: 'space-between' }}>
because I can rewrite NextUI component styles only with a "style", or via css using "!important". I don't think both options are good.
which one is better to use?

2023-01-25 13:25 UTC, Dergacz commented on src/utils/pokemonTypes.ts
> +export const pokemonTypes = [
You mean set the name to the className, and use the css to assign different colors?

2023-01-25 13:31 UTC, Dergacz commented on src/scenes/PokemonCard/PokemonCard.tsx
> +  const [{ color }] = pokemonTypes.filter(
> <img alt="image" width="285" src="https://user-images.githubusercontent.com/36301981/214314918-6d5fd998-0132-49d1-a37a-30bd07ef32bd.png">
> 
> Why you named it like this?)

Why not?) 
I think that the components are something reused, such as a button, etc., and this folder with pages
It's a bad practice?)

2023-01-25 13:39 UTC, Dergacz commented on src/scenes/Pokemon/Pokemon.tsx
> +  const [{ color }] = pokemonTypes.filter(
What are your suggestions?)

2023-01-25 14:17 UTC, melonholy commented on src/scenes/PokemonList/PokemonList.tsx
> +      <Grid.Container gap={2} style={{ justifyContent: 'space-between' }}>
https://nextui.org/docs/theme/override-styles

2023-02-01 11:34 UTC, merged